apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.email_email | b64enc | quote }}
  password: {{ .Values.email_password | b64enc | quote }}
