apiVersion: v1
kind: Secret
metadata:
  name: filter-redis-auth-secret
type: kubernetes.io/basic-auth
data:
  #username: {{ "No Username Required" | b64enc | quote }}
  password: {{ index .Values "filter-redis" "auth" "password" | b64enc | quote }}
