apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth-secret
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
