apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  private-key: {{ .Values.stripe_private_key | b64enc | quote }}
  webhook-secret: {{ .Values.stripe_webhook_secret | b64enc | quote }}
