apiVersion: v1
kind: Secret
metadata:
  name: subscriptions-ms-db-secret
type: kubernetes.io/basic-auth
data:
  username: {{ index .Values "subscriptions-ms-db" "auth" "rootUser" | b64enc | quote }}
  password: {{ index .Values "subscriptions-ms-db" "auth" "rootPassword" | b64enc | quote }}
