apiVersion: v1
kind: Secret
metadata:
  name: ws-redis-auth-secret
type: kubernetes.io/basic-auth
data:
  #username: {{ "No Username Required" | b64enc | quote }}
  password: {{ index .Values "ws-redis" "auth" "password" | b64enc | quote }}
