apiVersion: v1
kind: Service
metadata:
  name: orchestrator-ms-metrics
  labels:
    app: orchestrator-ms
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9121
      targetPort: 9121
  selector:
    name: orchestrator-ms
