{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: EXAMPLE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: EXAMPLE
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.production.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.production.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.production.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.production.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
