apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: EXAMPLE
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1 # $2
spec:
  rules:
    - http:
        paths:
          - path: /(.*) # (/|$)(.*)
            pathType: ImplementationSpecific # Prefix <- if no regex
            backend:
              service:
                name: EXAMPLE
                port:
                  number: 3000
